### PR TITLE
Fix grammar in jsonSpecs

### PR DESCRIPTION
**Pull request by dawnthefawn**
Remove " 's " from possessive nouns. This may seem like nitpicking at grammar, but this can cause errors while parsing these files while automating development, proper use of apostrophes aside.

### CODE REVIEW

**Comment by davidhbigelow** [comment]
This should not be required ... why are you experiencing a parsing problem?

What language - and what parser are you using?

Dave

**Comment by adama2000** [comment]
The json specs are generated automatically by a set of Java classes.  I will need to make these same changes in the Java code, otherwise the apostrophes would be restored next time the json specs are regenerated.

**Comment by dawnthefawn** [comment]
> The json specs are generated automatically by a set of Java classes. I will need to make these same changes in the Java code, otherwise the apostrophes would be restored next time the json specs are regenerated.

You know, I should have figured that was the case. I had the changes anyways cause I had already made them so I figured I'd submit. Sorry about that.

**Comment by dawnthefawn** [comment]
> This should not be required ... why are you experiencing a parsing problem?
> 
> What language - and what parser are you using?
> 
> Dave

It shouldn't be a problem, until you're working your way through the information you want from them and all your " become '. Then you have a problem. But whether or not that's a valid problem to have with it, its also just not correct. It is the combination of those two factors that warrant a change from my perspective.

**Comment by adama2000** [comment]
I don't understand your last comment.  Why would your " become ' ?  

Also, you only removed the possessive apostrophes, but there are a lot of other apostrophes in the JSON specs that would need removing too.

**Pull request closed without merging**
